export const tasks = [
    { id: 1, title: 'This is another task.', status: 'Done', dueDate: '2025-03-10', priority: 'High' },
    { id: 2, title: 'This is another task.', status: 'To-Do', dueDate: '2025-03-13', priority: 'Low' },
    { id: 3, title: 'This is another task.', status: 'In-Progress', dueDate: '2025-03-23', priority: 'Medium' },
    { id: 4, title: 'This is another task.', status: 'Done', dueDate: '2025-03-15', priority: 'High' },
    { id: 5, title: 'This is another task.', status: 'To-Do', dueDate: '2025-03-07', priority: 'Low' },
    { id: 6, title: 'This is another task.', status: 'In-Progress', dueDate: '2025-03-12', priority: 'Medium' },
    { id: 7, title: 'This is another task.', status: 'Done', dueDate: '2025-03-20', priority: 'High' },
    { id: 8, title: 'This is another task.', status: 'To-Do', dueDate: '2025-03-24', priority: 'Low' },
    { id: 9, title: 'This is another task.', status: 'In-Progress', dueDate: '2025-03-21', priority: 'Medium' },
    { id: 10, title: 'This is another task.', status: 'Done', dueDate: '2025-03-10', priority: 'High' },
    { id: 11, title: 'This is another task.', status: 'To-Do', dueDate: '2025-03-13', priority: 'Low' },
    { id: 12, title: 'This is another task.', status: 'In-Progress', dueDate: '2025-03-17', priority: 'Medium' },
    { id: 13, title: 'This is another task.', status: 'Done', dueDate: '2025-03-15', priority: 'High' },
    { id: 14, title: 'This is another task.', status: 'To-Do', dueDate: '2025-03-11', priority: 'Low' },
    { id: 15, title: 'This is another task.', status: 'In-Progress', dueDate: '2025-03-12', priority: 'Medium' },
    { id: 16, title: 'This is another task.', status: 'Done', dueDate: '2025-03-20', priority: 'High' },
    { id: 17, title: 'This is another task.', status: 'To-Do', dueDate: '2025-03-24', priority: 'Low' },
    { id: 18, title: 'This is another task.', status: 'In-Progress', dueDate: '2025-03-09', priority: 'Medium' },
    { id: 19, title: 'This is another task.', status: 'In-Progress', dueDate: '2025-03-24', priority: 'Low' },
    { id: 20, title: 'This is another task.', status: 'Done', dueDate: '2025-03-15', priority: 'Medium' },
];